.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. becoin_qt test_becoin_qt
clean: FORCE
	$(MAKE) -C .. becoin_qt_clean test_becoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_becoin_qt_check
becoin-qt becoin-qt.exe: FORCE
	 $(MAKE) -C .. becoin_qt
