description "BeCoin Core Daemon"

start on runlevel [2345]
stop on starting rc RUNLEVEL=[016]

env BECOIND_BIN="/usr/bin/becoind"
env BECOIND_USER="becoin"
env BECOIND_GROUP="becoin"
env BECOIND_PIDDIR="/var/run/becoind"
# upstart can't handle variables constructed with other variables
env BECOIND_PIDFILE="/var/run/becoind/becoind.pid"
env BECOIND_CONFIGFILE="/etc/becoin/becoin.conf"
env BECOIND_DATADIR="/var/lib/becoind"

expect fork

respawn
respawn limit 5 120
kill timeout 60

pre-start script
    # this will catch non-existent config files
    # becoind will check and exit with this very warning, but it can do so
    # long after forking, leaving upstart to think everything started fine.
    # since this is a commonly encountered case on install, just check and
    # warn here.
    if ! grep -qs '^rpcpassword=' "$BECOIND_CONFIGFILE" ; then
        echo "ERROR: You must set a secure rpcpassword to run becoind."
        echo "The setting must appear in $BECOIND_CONFIGFILE"
        echo
        echo "This password is security critical to securing wallets "
        echo "and must not be the same as the rpcuser setting."
        echo "You can generate a suitable random password using the following"
        echo "command from the shell:"
        echo
        echo "bash -c 'tr -dc a-zA-Z0-9 < /dev/urandom | head -c32 && echo'"
        echo
        echo "It is also recommended that you also set alertnotify so you are "
        echo "notified of problems:"
        echo
        echo "ie: alertnotify=echo %%s | mail -s \"BeCoin Alert\"" \
            "admin@foo.com"
        echo
        exit 1
    fi

    mkdir -p "$BECOIND_PIDDIR"
    chmod 0755 "$BECOIND_PIDDIR"
    chown $BECOIND_USER:$BECOIND_GROUP "$BECOIND_PIDDIR"
    chown $BECOIND_USER:$BECOIND_GROUP "$BECOIND_CONFIGFILE"
    chmod 0660 "$BECOIND_CONFIGFILE"
end script

exec start-stop-daemon \
    --start \
    --pidfile "$BECOIND_PIDFILE" \
    --chuid $BECOIND_USER:$BECOIND_GROUP \
    --exec "$BECOIND_BIN" \
    -- \
    -pid="$BECOIND_PIDFILE" \
    -conf="$BECOIND_CONFIGFILE" \
    -datadir="$BECOIND_DATADIR" \
    -disablewallet \
    -daemon

